version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies (if any)"
  pre_build:
    commands:
      - echo "Preparing build..."
  build:
    commands:
      - echo "✅ Printing contents of message.txt"
      - cat message.txt
  post_build:
    commands:
      - echo "Build finished"
